### ISSUE TITLE
Is the initial state needed here?

### ISSUE THREAD

**Issue by trajkovvlatko** [tstringer/create-react-app-with-redux#1]
It seems like it's always "undefined".

https://github.com/tstringer/create-react-app-with-redux/blob/master/src/store/configure-store.js#L4

Even when the configure state is invoked, it doesn't pass any parameters:
https://github.com/tstringer/create-react-app-with-redux/blob/master/src/index.js#L8

Thanks!

**Comment by trstringer** [comment]
Good point. No initial state is not used or needed, but I wanted the basics to be there for future use. You could inject inital state though if you like.

**Comment by trajkovvlatko** [comment]
Great. Thanks for the info!
